### ISSUE TITLE
Android Build Failed

### ISSUE THREAD

**Issue by jsappme** [jeduan/cordova-plugin-facebook4#11]
With the following error:

UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lbolts/AggregateException;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)

Any idea why?

**Comment by jeduan** [comment]
Apparently you have many libraries that include Bolts. Check if any plugins are adding bolts.jar and delete it

**Comment by jsappme** [comment]
You are completely right. I have this plugin https://github.com/grrrian/phonegap-parse-plugin that is conflicting with the FB plugin. But I need the Parse plugin for the Push Notification. Any idea how to solve this Bolts conflict with removing the Parse Plugin?

**Comment by jeduan** [comment]
Unfortunately is one of the reasons I'm forking lots of plugins: to let Gradle handle the dependencies. You could fork the plugin and replace the jar with a <framework> tag in plugin.xml. That way it will do everything right for you.

**Comment by jsappme** [comment]
Sorry Jeduan. I am not sure to understand. Should I fork your plugin or the Parse plugin? How do I replace the jar with the <framework> tag? Right on on your plugin I have : 


<framework src="src/ios/FBSDKCoreKit.framework" custom="true" />
<framework src="src/ios/FBSDKLoginKit.framework" custom="true" />
<framework src="src/ios/FBSDKShareKit.framework" custom="true" />

**Comment by jsappme** [comment]
I still don't understand why the iOs version is working good but not the Android version.

**Comment by manuelpaulo** [comment]
I am having the same problem with a different plugin 

UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)

**Comment by jeduan** [comment]
@jsappme It's working fine on iOS because on iOS the Facebook SDK is a static library which creates a sort of namespace, and on Android it tries to reuse the same JARs for everything.

What I meant is to fork the Parse plugin, removing their JAR and the entry on plugin.xml and replacing with a framework tag on the `<platform name="android">` section like so
```xml
<framework src="com.parse.bolts:bolts-android:1.2.0">
```

This commit is a good reference: https://github.com/jeduan/cordova-plugin-push-notification/commit/79ea57bf8754f67b06e8aba571f6dc3845190390

**Comment by jeduan** [comment]
@manuelpaulo Same instructions for you. Actually it's even the same JAR causing problem.

**Comment by jeduan** [comment]
Closing since this is not an issue with this plugin.

**Comment by redplane** [comment]
Same issue happened to `ionic 4` and `cordova-plugin-facebook4 4.2.1`.

This is my configuration in `package.json`:

```
"cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-sqlite-storage": {},
      "phonegap-plugin-barcodescanner": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-nativestorage": {},
      "cordova-plugin-customurlscheme": {
        "URL_SCHEME": "ionic-sso",
        "ANDROID_SCHEME": " ",
        "ANDROID_HOST": " ",
        "ANDROID_PATHPREFIX": "/"
      },
      "cordova-plugin-googleplus": {
        "REVERSED_CLIENT_ID": "com.googleusercontent.apps.323676358406-jkd0pi3g4977dir0mh1fpq24ggg3kemh",
        "WEB_APPLICATION_CLIENT_ID": "...",
        "PLAY_SERVICES_VERSION": "..."
      },
      "cordova-plugin-facebook4": {
        "APP_ID": "...",
        "APP_NAME": "..."
      }
    },
```
