### ISSUE TITLE
App crashes at launch in production

### ISSUE THREAD

**Issue by aldryss** [jeduan/cordova-plugin-facebook4#128]
I published a new Android version of my app (who previously used wizcorp plugin) with this version of the plugin, so I could use the facebook app invite.

It ran without problems during the development phase, but after building it for release and publishing the new version, no users could launch the application. I had to unpublish it and can't really figure the problem.

Here's the stacktrace

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/FacebookActivity;
	at com.facebook.internal.Validate.hasFacebookActivity(Validate.java:175)
	at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:198)
	at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:174)
	at org.apache.cordova.facebook.ConnectPlugin.pluginInitialize(ConnectPlugin.java:81)
	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:55)
	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:95)
	at org.apache.cordova.PluginManager.init(PluginManager.java:84)
	at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:138)
	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:208)
	at com.selectionnist.m.MainActivity.onCreate(MainActivity.java:32)
	at android.app.Activity.performCreate(Activity.java:6289)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2760)
	at android.app.ActivityThread.access$900(ActivityThread.java:177)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5944)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookActivity" on path: DexPathList[[zip file "/data/app/com.selectionnist.m-1/base.apk"],nativeLibraryDirectories=[/data/app/com.selectionnist.m-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 25 more
	Suppressed: java.lang.NoClassDefFoundError: com.facebook.FacebookActivity
		at dalvik.system.DexFile.defineClassNative(Native Method)
		at dalvik.system.DexFile.defineClass(DexFile.java:226)
		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
		at dalvik.system.DexPathList.findClass(DexPathList.java:321)
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
		... 27 more
	Suppressed: java.lang.ClassNotFoundException: com.facebook.FacebookActivity
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 26 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by jeduan** [comment]
> Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

Looks like gradle didn't compile the Facebook SDK into the jar. Probably trying again will solve the problem.

**Comment by aldryss** [comment]
Yep, the sdk is not in the apk, can't find it in builds/release, rebuilding doesn't change it. I can't delete the platform because the dev who made the project totally fucked it. I'm trying to find why it won't compile the sdk in release mode

**Comment by aldryss** [comment]
Cleaned the build folder of my android platform and rebuilt the whole thing, my app is now back on the store. Thanks for the hint and good job with your plugin btw :)
