### ISSUE TITLE
Trouble installing on platform ios

### ISSUE THREAD

**Issue by barocsi** [jeduan/cordova-plugin-facebook4#150]
Command
```
$ cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="xxxx" --variable APP_NAME="xxxx"
```
result
```
Failed to install 'cordova-plugin-facebook4':TypeError: Cannot read property 'nodeName' of null
    at Object.parse (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/parse.js:45:26)
    at Object.module.exports.package_name (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:143:22)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:270:67
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:857:14
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:419:9)
Error: Cannot read property 'nodeName' of null
```

I have the following plugins installed:

```
cordova-plugin-camera
cordova-plugin-device
cordova-plugin-file
cordova-plugin-sim
cordova-plugin-statusbar
cordova-plugin-whitelist
cordova-plugin-x-socialsharing
io.branch.sdk
ionic-plugin-keyboard
phonegap-plugin-push
```
Cordova ios platform version: 3.9.2.

**Comment by ArthurClemens** [comment]
I also cannot install on iOS, but I am getting a different error:

~~~
$ cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="XXX" --variable APP_NAME="ABC"
Fetching plugin "cordova-plugin-facebook4" via npm
Installing "cordova-plugin-facebook4" for ios
Failed to install 'cordova-plugin-facebook4':TypeError: Uh oh!
buildSettings.FRAMEWORK_SEARCH_PATHS.push is not a function
    at pbxProject.addToFrameworkSearchPaths (/Users/arthur/code/ABC/Cordova/abc/platforms/ios/cordova/node_modules/xcode/lib/pbxProject.js:979:49)
    at pbxProject.addFramework (/Users/arthur/code/ABC/Cordova/abc/platforms/ios/cordova/node_modules/xcode/lib/pbxProject.js:278:14)
    at handlers.framework.install (/Users/arthur/code/ABC/Cordova/abc/platforms/ios/cordova/lib/plugman/pluginHandlers.js:87:41)
    at Object.ActionStack.process (/Users/arthur/code/ABC/Cordova/abc/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at Plugman.addPlugin (/Users/arthur/code/ABC/Cordova/abc/platforms/ios/cordova/lib/plugman/Plugman.js:82:20)
    at Api.addPlugin (/Users/arthur/code/ABC/Cordova/abc/platforms/ios/cordova/Api.js:187:53)
    at handleInstall (/Users/arthur/.npm/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:601:6)
    at /Users/arthur/.npm/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:385:28
    at _fulfilled (/Users/arthur/.npm/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/arthur/.npm/lib/node_modules/cordova/node_modules/q/q.js:816:30)
Error: Uh oh!
buildSettings.FRAMEWORK_SEARCH_PATHS.push is not a function
~~~

**Comment by aferrerallu** [comment]
@barocsi:

readme file says Compatibility Cordova v5.0.0. So your 3.9.2 cordova is the problem.

**Comment by barocsi** [comment]
Sorry, that was Cordova platform ios version, not cordova CLI
