### ISSUE TITLE
Erro unexpected  in Phonegap Build for android

### ISSUE THREAD

**Issue by ivanssa** [jeduan/cordova-plugin-facebook4#158]
I am unable to compile an app because of an unexpected error that began to occur this week in build.phonegap site when trying to compile my app the site refuses to compile and displays the following error: "Oh geez Your build failed Sorry,.. but a problem occurred on the build server "to remove the entry of the plugin I can compile so I am writing to know how to solve ...
I am using the following entry in config.xml 

```
<plugin name="cordova-plugin-facebook4" source="npm" spec="1.4.0" >
		<param name="APP_ID" value="myappid" />
		<param name="APP_NAME" value="myappname" />
</plugin>
```

and I get the following error log:

```

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/android-sdk/build-tools/23.0.1/dx --dex --no-optimize --output /project/build/intermediates/dex/debug --input-list=/project/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 6.261 secs

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /project/gradlew with args: cdvBuildDebug,-b,/project/build.gradle,-Dorg.gradle.daemon=true
	
```

**Comment by ivanssa** [comment]
Personally, I found that the error occurs with a plugin conflict so I was removing one by one until you find the version of cord-plugin-background-geolocation plugin that gave conflict with facebook4 was only update the version of the plugin background that compiled correctly, sorry my confusion, is a tip for those who have the same problem hugs ...

**Comment by crazybaud** [comment]
@ivanssa How did you solve the conflict problem between those 2 plugins ?

**Comment by rhengles** [comment]
I'm also having this problem...

In my case I have:

```xml
    <gap:plugin name="com.adobe.plugins.gaplugin" src="git" version="https://github.com/phonegap-build/GAPlugin.git#2.4.0" />
    <gap:plugin name="cordova-plugin-facebook4" src="git" version="https://github.com/jeduan/cordova-plugin-facebook4.git#v0.11.0">
        <param name="android-package" value="facebookConnectPlugin" />
        <param name="APP_ID" value="---redacted---" />
        <param name="APP_NAME" value="---redacted---" />
    </gap:plugin>
```
