### ISSUE TITLE
Null Pointer Exception : Argument 'context' cannot be null

### ISSUE THREAD

**Issue by akinorikul** [jeduan/cordova-plugin-facebook4#244]
Hi, 
I get this crash report : 

Caused by: java.lang.NullPointerException: Argument 'context' cannot be null
 at com.facebook.internal.Validate.notNull(Validate.java:76)
 at com.facebook.internal.Utility.getMetadataApplicationId(Utility.java:594)
 at com.facebook.appevents.AppEventsLogger.<init>(AppEventsLogger.java:757)
 at com.facebook.appevents.AppEventsLogger.<init>(AppEventsLogger.java:732)
 at com.facebook.appevents.AppEventsLogger.newLogger(AppEventsLogger.java:400)
 at org.apache.cordova.facebook.ConnectPlugin.pluginInitialize(ConnectPlugin.java:88)
 at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
 at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:172)
 at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:98)
 at org.apache.cordova.PluginManager.init(PluginManager.java:87)
 at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
 at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:144)
 at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:214)
 at com.zoomupdev.app.MainActivity.onCreate(MainActivity.java:32)
 at android.app.Activity.performCreate(Activity.java:5104)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
 at android.app.ActivityThread.access$600(ActivityThread.java:141) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
 at android.os.Handler.dispatchMessage(Handler.java:99) 
 at android.os.Looper.loop(Looper.java:137) 
 at android.app.ActivityThread.main(ActivityThread.java:5041) 
 at java.lang.reflect.Method.invokeNative(Native Method) 
 at java.lang.reflect.Method.invoke(Method.java:511) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
 at dalvik.system.NativeStart.main(Native Method) 

My app was working well till today, I don't know why I get that error now.

**Comment by Florian9-3** [comment]
Same for me. Any solution for this?

**Comment by Florian9-3** [comment]
There seems to be a problem with the latest facebook SDK:
[Stackoverflow](http://stackoverflow.com/questions/37878370/argument-context-cannot-be-null)

**Workaround:**
In plugin.xml change this line
`<framework src="com.facebook.android:facebook-android-sdk:4.+"/>`
to this
`<framework src="com.facebook.android:facebook-android-sdk:4.12.1"/>`

Eventually you have to change the version in the project.properties in the platforms/android directory to com.facebook.android:facebook-android-sdk:4.12.1 as well.

**Comment by robertarnesson** [comment]
might as well go with 4.13.1: https://developers.facebook.com/docs/ios/change-log-4.x

if someone wants to prep a PR that would be super, if not I'll try to get to it the coming days

**Comment by robertarnesson** [comment]
4.13.1 is now in master.
