### ISSUE TITLE
Wrong path in new after_prepare hook

### ISSUE THREAD

**Issue by nickbecker** [jeduan/cordova-plugin-facebook4#317]
It needs the 'www/' in the path.

Error: ENOENT: no such file or directory, open 'c:\BuildAgent2\work\a3a2b29a23632dba\config.xml'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (c:\BuildAgent2\work\a3a2b29a23632dba\plugins\cordova-plugin-facebook4\scripts\after_prepare.j
s:18:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by robertarnesson** [comment]
the config file should be in the project root. what is your dir structure?

**Comment by nickbecker** [comment]
Ahhh, my mistake.  We used an open source template project structure that had it in the www folder.
