### ISSUE TITLE
Error: Variable(s) missing: APP_ID, APP_NAME

### ISSUE THREAD

**Issue by Ruff9** [jeduan/cordova-plugin-facebook4#409]
It seems like a common issue, but I couldn't find any solution. I'm using Cordova 6.4.0.

The plugin was installed with this command:

```
cordova plugin add --save cordova-plugin-facebook4 --variable APP_ID="my_app_id" --variable APP_NAME="my_app_name"
```

The app was successfully build locally, and my colleague made it working in an emulator. But when he pushed it on our CI (GreenhouseCI), the build succeed for the android app, but not for the ios app.

The error:

```
Installing "cordova-plugin-facebook4" for ios
Failed to install 'cordova-plugin-facebook4':Error: Variable(s) missing: APP_ID, APP_NAME
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:362:23
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Variable(s) missing: APP_ID, APP_NAME
```

We can find these variables in config.xml:

```
<plugin name="cordova-plugin-facebook4" spec="~1.7.4">
    <variable name="APP_ID" value="my_app_id" />
    <variable name="APP_NAME" value="my_app_name" />
</plugin>
```

and also in plugins/fetch.json:

```
"cordova-plugin-facebook4": {
    "source": {
        "type": "registry",
        "id": "cordova-plugin-facebook4"
    },
    "is_top_level": true,
    "variables": {
        "APP_ID": "my_app_id",
        "APP_NAME": "my_app_name"
    }
}
```

I found a possible solution [here](http://stackoverflow.com/a/28818121/3219759) : edit the `plugins\com.phonegap.plugins.facebookconnect\plugins.xml` file. I have a problem with this : I don't check the plugins directory into version control.

**Comment by evyatar** [comment]
try to remove and re-add the plugin as suggested on the project page 

> If you need to change your APP_ID after installation, it's recommended that you remove and then re-add the plugin as above. Note that changes to the APP_ID value in your config.xml file will not be propagated to the individual platform builds.

**Comment by foxxx** [comment]
+1

**Comment by argustinelli** [comment]
I have the same problem!!!

**Comment by jhonatasfender** [comment]
I also have the same problem, but for android:
`
        Installing "cordova-plugin-facebook4" for android
        Failed to install 'cordova-plugin-facebook4': Error: Variable(s) missing: APP_ID, APP_NAME
             at /opt/node/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:334:23
             at _fulfilled (/opt/node/lib/node_modules/cordova/node_modules/q/q.js:787:54)
             at self.promiseDispatch.done (/opt/node/lib/node_modules/cordova/node_modules/q/q.js:816:30)
             at Promise.promise.promiseDispatch (/opt/node/lib/node_modules/cordova/node_modules/q/q.js:749:13)
             at /opt/node/lib/node_modules/cordova/node_modules/q/q.js:557:44
             at flush (/opt/node/lib/node_modules/cordova/node_modules/q/q.js:108:17)
             at _combinedTickCallback (internal/process/next_tick.js:73:7)
             at process._tickCallback (internal/process/next_tick.js:104:9)
        Error: Variable(s) missing: APP_ID, APP_NAME
`

**Comment by peterpeterparker** [comment]
This question is older than a year, no problem here. For cordova-android@7 compatibility see the `Android guide`

For support questions plz use other channels like Stackoverflow or Ionic forum
