### ISSUE TITLE
Does this plugin supports Android 7 (API level 25)?

### ISSUE THREAD

**Issue by Ajeetlakhani** [jeduan/cordova-plugin-facebook4#473]

**Comment by NadirBertolasi** [comment]
Hi, I have an error on Galaxy s8 with Android API level 25. This is the exception thrown by Android:

```
05-13 18:29:02.223 22398-22398/it.my.app E/Activity: Error: SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: Errors while executing operation "ProxyAuthAppLoginStartQuery": At Query.proxy_auth_app_login_start: Failed to resolve field.
05-13 18:29:02.223 22398-22398/it.my.app E/ConnectPlugin: SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: Errors while executing operation "ProxyAuthAppLoginStartQuery": At Query.proxy_auth_app_login_start: Failed to resolve field.
05-13 18:29:02.560 3727-3821/? E/WindowManager: Unhandled exception in Window Manager
                                                java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
                                                    at java.util.ArrayList.get(ArrayList.java:411)
                                                    at com.android.server.wm.WindowAnimator.updateAppWindowsLocked(WindowAnimator.java:249)
                                                    at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:946)
                                                    at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                                                    at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:181)
                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:957)
                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                    at android.view.Choreographer.doFrame(Choreographer.java:667)
                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:154)
                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                    at com.android.server.ServiceThread.run(ServiceThread.java:46)
05-13 18:29:04.139 4097-608/? E/HeadsetStateMachine: Unknown message: 11
05-13 18:29:04.971 3727-5646/? E/ApfFilter: Error parsing RA: java.lang.IllegalArgumentException: Bad position 1494/86
05-13 18:29:06.882 3727-4072/? E/WifiWatchdogStateMachine: Unhandled message { when=0 what=135238 target=com.android.internal.util.StateMachine$SmHandler } in state ValidNonSwitchableState
05-13 18:29:10.912 3727-5646/? E/ApfFilter: Error parsing RA: java.lang.IllegalArgumentException: Bad position 1614/86
```

**Comment by snakeman21** [comment]
I have Android 7 and it works for me. Try downgrading versions

**Comment by peterpeterparker** [comment]
Yep it does support, recently tested was fine
