### ISSUE TITLE
Cannot remove cordova-plugin-facebook4 1.3

### ISSUE THREAD

**Issue by johnrobertcobbold** [jeduan/cordova-plugin-facebook4#49]
Trying to remove 1.3 so that I can install 1.4. But when entering  :
`ionic plugin remove cordova-plugin-facebook4`

I am getting :
`TypeError: Cannot read property 'buffer' of undefined
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:131:18)
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:98:7)
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:109:9)
    at Object.build (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:76:3)
    at ConfigFile_save [as save] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigFile.js:97:47)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:61:49
    at Array.forEach (native)
    at ConfigKeeper_save_all [as save_all] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:59:31)
    at PlatformMunger_save_all [as save_all] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:82:24)
    at Object.exports.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:59:12)`

**Comment by jeduan** [comment]
seems like a bug in `cordova-cli` or `ionic`. Shouldn't this bug be raised there?

**Comment by Hirbod** [comment]
It is. Will be fixed (there is already a pr in jira). You will need to platform rm ios while we waiting for a cli fix

**Comment by dbroadhurst** [comment]
I found if I remove a second time its removed without error. Not sure its completely gone away but you can reinstall without any complaints about its already been installed.

**Comment by stubailo** [comment]
@Hirbod is there an issue on GitHub somewhere we can keep track of?

**Comment by stubailo** [comment]
I guess it's this one: https://issues.apache.org/jira/browse/CB-7781

**Comment by Hirbod** [comment]
Right this is it

**Comment by bau720123** [comment]
I have the totally same problem with cordova 6.0 cli

**Comment by jeduan** [comment]
This is a bug in cordova-cli. FWIW, I set everything up in config.xml so that I can remove `platforms` and `plugins` at any time and just reinstall them from that file with `cordova prepare`

**Comment by ArthurClemens** [comment]
What solved it for me:

* rename ios folder to _ios
* `cordova plugin rm cordova-plugin-facebook4`
* rename folder _ios to ios

**Comment by andreyzenkov** [comment]
Guys, I had this issue in cordova 5.3. Installed cordova 5.4 and removed plugin and after installed cordova 5.3.3 :) I hope it will help somebody.

**Comment by FarhanSaleem** [comment]
I had the same issue couldnt remove the platform or the plugin...really frustrating. I ended up running cordova plugin add <--plugin--> --save and this updated the plugin to the latest version...hope this helps someone
