### ISSUE TITLE
proper way to request manage_pages

### ISSUE THREAD

**Issue by juszczec** [jeduan/cordova-plugin-facebook4#491]
Hello 

I have added 'manage_pages' to my login parameters

        facebookConnectPlugin.login([
          'user_events', 'public_profile', 'email', 'manage_pages'
        ],        
        onLoginSuccess,
        onLoginFail);

However, this fails and in the log I see:

05-07 13:42:14.636 20130-20219/com.mj.dropin E/PluginManager: Uncaught exception from plugin
                                                              Cannot pass a publish or manage permission (manage_pages) to a request for read authorization
                                                                  at com.facebook.login.LoginManager.validateReadPermissions(LoginManager.java:368)
                                                                  at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:308)
                                                                  at org.apache.cordova.facebook.ConnectPlugin.executeLogin(ConnectPlugin.java:723)
                                                                  at org.apache.cordova.facebook.ConnectPlugin.execute(ConnectPlugin.java:279)
                                                                  at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
                                                                  at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
                                                                  at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
                                                                  at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
                                                                  at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                  at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)

What is the proper way to request manage_pages authorization on android & iOS?

Do I have to do this by calling this method I found in facebook-native.js:

    exports.getAccessToken = function getAccessToken (s, f) {
      exec(s, f, 'FacebookConnectPlugin', 'getAccessToken', [])
    }

If so, how do I give it manage_pages permissions?

I've also found [https://github.com/jeduan/cordova-plugin-facebook4/issues/54](url) where lichutin suggests something like:

    //login
                        facebookConnectPlugin.login(['user_about_me', 'user_birthday', 'email' ], function (result) {
                            showDialog();
                        }, function (err) {
                            console.log('login error', err);
                        });

    //showDialog body
                    facebookConnectPlugin.getAccessToken(function (token) {
                        facebookConnectPlugin.api(
                                'me/dirtyHack',
                                ['publish_pages', 'manage_pages', 'publish_actions'],
                                function (res)
                                {
                                    console.log('yeah', res);
                                },
                                function (err)
                                {
                                    console.log('fail', err);
                                });
                    });

                    facebookConnectPlugin.showDialog(
                            data, function (result) {
                                callback && callback(result);
                            }, function (err) {
                        error && error(err);
                    }
                    );

Is that the proper way to request manage_pages permission?

**Comment by peterpeterparker** [comment]
Close it because old issue. For support inquiries plz use other channels like Stackoverflow, thx
