### ISSUE TITLE
Login fails on Android 5.1.1

### ISSUE THREAD

**Issue by jblamber** [jeduan/cordova-plugin-facebook4#533]
Can't quite figure out why the facebook login activity crashes. The login dialog works on my Android 7.0 device both with and without the facebook app (native & web). But the same code running on a 5.1.1 device will only work if the facebook app is not installed - the native activity crashes? I see a facebook dialog open for a split second before it closes again. Adb output shows the following:

```
D/ConnectPlugin(26366): login FB
D/ConnectPlugin(26366): activity result in plugin: requestCode(64206), resultCode(-1)
E/Activity(26366): Error: SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: Errors while executing operation "ProxyAuthAppLoginStartQuery": At Query.proxy_auth_app_login_start: Failed to resolve field.
E/ConnectPlugin(26366): SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: Errors while executing operation "ProxyAuthAppLoginStartQuery": At Query.proxy_auth_app_login_start: Failed to resolve field.
W/System.err(26366): org.json.JSONException: Unterminated object at character 142 of {"errorMessage": "Facebook error: SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: Errors while executing operation "ProxyAuthAppLoginStartQuery": At Query.proxy_auth_app_login_start: Failed to resolve field."}
W/System.err(26366):    at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
W/System.err(26366):    at org.json.JSONTokener.readObject(JSONTokener.java:394)
W/System.err(26366):    at org.json.JSONTokener.nextValue(JSONTokener.java:100)
W/System.err(26366):    at org.json.JSONObject.<init>(JSONObject.java:156)
W/System.err(26366):    at org.json.JSONObject.<init>(JSONObject.java:173)
W/System.err(26366):    at org.apache.cordova.facebook.ConnectPlugin.getErrorResponse(ConnectPlugin.java:976)
W/System.err(26366):    at org.apache.cordova.facebook.ConnectPlugin.handleError(ConnectPlugin.java:835)
W/System.err(26366):    at org.apache.cordova.facebook.ConnectPlugin.access$300(ConnectPlugin.java:57)
I/Activity(26366): Activity.onPostResume() called
W/System.err(26366):    at org.apache.cordova.facebook.ConnectPlugin$2.onError(ConnectPlugin.java:136)
W/System.err(26366):    at com.facebook.login.LoginManager.finishLogin(LoginManager.java:628)
W/System.err(26366):    at com.facebook.login.LoginManager.onActivityResult(LoginManager.java:237)
W/System.err(26366):    at com.facebook.login.LoginManager$1.onActivityResult(LoginManager.java:166)
W/System.err(26366):    at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:86)
W/System.err(26366):    at org.apache.cordova.facebook.ConnectPlugin.onActivityResult(ConnectPlugin.java:275)
W/System.err(26366):    at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:152)
W/System.err(26366):    at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:358)
W/System.err(26366):    at android.app.Activity.dispatchActivityResult(Activity.java:6258)
W/System.err(26366):    at android.app.ActivityThread.deliverResults(ActivityThread.java:3684)
W/System.err(26366):    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3731)
W/System.err(26366):    at android.app.ActivityThread.access$1300(ActivityThread.java:162)
W/System.err(26366):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
W/System.err(26366):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(26366):    at android.os.Looper.loop(Looper.java:135)
W/System.err(26366):    at android.app.ActivityThread.main(ActivityThread.java:5422)
W/System.err(26366):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(26366):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(26366):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
W/System.err(26366):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

This is with cordova 6.4.0 in an ionic v1 app.

Any insight people might offer as to why this android version specific issues shows up would be appreciated. Ill keep debugging in the meantime.

**Comment by jblamber** [comment]
Of course I fix it within minutes of posting this - but for those who face the same issue.

My facebook application was in private mode, and my android 7.0 device was using my personal account, which is allowed. However the android 5.1.1 device was using a separate facebook account. Only specifically allowed users can access the app while in private mode. To fix this (taken from https://stackoverflow.com/questions/41861564/server-error-code-1675030-message-error-performing-query) 

Either:

Add users to the tester roles
Go to app-review and make public.
