### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by allancmello** [jeduan/cordova-plugin-facebook4#557]
ionic cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="370144230085198" --variable APP_NAME="FlaVV"

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'file:node_modules\\cordova-plugin-facebook4',
1 verbose cli   '--save' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose npm-session 76b0fb00d576d25e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for file:node_modules\cordova-plugin-facebook4 Could not install from "node_modules\cordova-plugin-facebook4" as it does not contain a package.json file.
8 verbose stack Error: ENOENT: no such file or directory, open 'D:\ionic\FlaVV\node_modules\node_modules\cordova-plugin-facebook4\package.json'
9 verbose cwd D:\ionic\FlaVV\node_modules
10 verbose Windows_NT 10.0.15063
11 verbose argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "file:node_modules\\cordova-plugin-facebook4" "--save"
12 verbose node v8.1.3
13 verbose npm  v5.0.3
14 error code ENOLOCAL
15 error Could not install from "node_modules\cordova-plugin-facebook4" as it does not contain a package.json file.
16 verbose exit [ 1, true ]

What is wrong?

**Comment by sunojvijayan** [comment]
Same thing is happening for me now. Last month it was working fine. But today it shows this error

Error: Failed to fetch plugin file:node_modules/cordova-plugin-facebook4 via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 1 Error output:
        npm ERR! code ENOLOCAL
        npm ERR! Could not install from "node_modules/cordova-plugin-facebook4" as it does not contain a package.json
        file.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /Users/username/.npm/_logs/2017-10-31T08_27_52_666Z-debug.log

**Comment by ljfreelancer88** [comment]
It happened to me as well.

**Comment by jimcamut** [comment]
Any fix on this? I'm getting the same error.

**Comment by abrowne2** [comment]
I was able to fix this by going into my package.json and checking "cordova-plugin-facebook4", where the dependencies object had "cordova-plugin-facebook4" pointing to a file and not the version "^1.9.1". Not sure how the package file overwrote this or why it stopped working.

**Comment by VozaxDev** [comment]
getting this error
ionic cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID = "324069978316346" --variable APP_NAME = "firstApp" --verbose
  ionic:lib Terminal info: { tty: true, ci: false, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'cordova', 'plugin', 'add', 'cordova-plugin-facebook4', '=', '324069978316346', '=', 'firstApp' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, save: true, variable: [ 'APP_ID', 'APP_NAME' ], project: null, '--': [] } +5ms
  ionic:lib:project Project type from config: Ionic 2/3 (ionic-angular) +0ms
  ionic:lib:project Project details: { configPath: '/Users/lucky/Documents/projects/Ehtisham/CRUD firebase /crud/ionic.config.json', errors: [], context: 'app', type: 'ionic-angular'} +1ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/ionic/bin/ionic', libPath: '/usr/local/lib/node_modules/ionic', execPath: '/Users/lucky/Documents/projects/Ehtisham/CRUD firebase /crud', version: '4.6.0' } +0ms
  ionic:lib:integrations:cordova:config Using config.xml: /Users/lucky/Documents/projects/Ehtisham/CRUD firebase /crud/config.xml +0ms
> cordova plugin add cordova-plugin-facebook4 = 3240699783187484 = firstApp --verbose --variable APP_ID --variable APP_NAME --save
  ionic:lib:telemetry Sending telemetry for command: 'ionic cordova plugin' [ 'add',
  ionic:lib:telemetry   'cordova-plugin-facebook4',
  ionic:lib:telemetry   '=',
  ionic:lib:telemetry   '324069978316346',
  ionic:lib:telemetry   '=',
  ionic:lib:telemetry   'firstApp',
  ionic:lib:telemetry   '--verbose',
  ionic:lib:telemetry   '--interactive',
  ionic:lib:telemetry   '--color',
  ionic:lib:telemetry   '--save',
  ionic:lib:telemetry   '--variable=APP_ID',
  ionic:lib:telemetry   '--variable=APP_NAME' ] +0ms
invalid variable format: APP_ID
CordovaError: invalid variable format: APP_ID
    at /Users/lucky/Documents/projects/Ehtisham/CRUD firebase /crud/node_modules/cordova/src/cli.js:435:27
    at Array.forEach (<anonymous>)
    at cli (/Users/lucky/Documents/projects/Ehtisham/CRUD firebase /crud/node_modules/cordova/src/cli.js:431:27)
    at /Users/lucky/Documents/projects/Ehtisham/CRUD firebase /crud/node_modules/cordova/src/cli.js:203:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
[ERROR] An error occurred while running subprocess cordova.

        cordova plugin add cordova-plugin-facebook4 = 32406997854584 = firstApp --verbo... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:cli-framework:utils:process onBeforeExit handler: process.exit received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 1 functions +12ms
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 1) +41ms
