### ISSUE TITLE
Ionic - cordova-android 7.0, "Could not resolve all files for configuration ':app:debugCompileClasspath'."

### ISSUE THREAD

**Issue by breadam** [jeduan/cordova-plugin-facebook4#673]
```
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild

FAILED

14 actionable tasks: 1 executed, 13 up-to-date
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find runtime.aar (android.arch.lifecycle:runtime:1.0.3).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/lifecycle/runtime/1.0.3/runtime-1.0.3.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BU�LD FAILED in 7s
(node:17112) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find runtime.aar (android.arch.lifecycle:runtime:1.0.3).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/lifecycle/runtime/1.0.3/runtime-1.0.3.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BU�LD FAILED in 7s
    at ChildProcess.whenDone (C:\Users\breadam\Desktop\proj\muchfame\muchfame\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:17112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[OK] Your app has been deployed.
     Did you know you can live-reload changes from your app with --livereload?

```
Help please, thanks

**Comment by breadam** [comment]
Closing for now, I'll try something and reopen if necessary

**Comment by breadam** [comment]
Nope, couldn't find a solution. After removing cordova-plugin-facebook4 everything works fine. Can't figure out what problem is

**Comment by breadam** [comment]
I've already added app id and name to config.xml, and still got error anyways. But yeah i think i should ask this on SO. Thank you, ciao :)

**Comment by peterpeterparker** [comment]
Thx. Maybe a spontaneous idea is updating cordova itself too if you might use an old version, but not sure if that could solve it or not, just an idea

**Comment by OBout** [comment]
`cordova platform add android@6.4.0 `works for me. It is my magic wand.
