### ISSUE TITLE
[Android] Login dialog cancel crashes the app

### ISSUE THREAD

**Issue by msokk** [jeduan/cordova-plugin-facebook4#7]
Hi,

First of all, thanks for the great work of updating the plugin.

Our app crashes if the user cancels the login dialog. Device is running Lollipop 5.1.

`handleError` method logging at line 120 fails if exception is the type of `FacebookOperationCanceledException`, because the message and `toString()` is null.
Seems there are more messageless exception types in SDK, so probably should wrap the logger.

Here's the exception happening:
https://www.dropbox.com/s/xp47cdr4vo8mz79/Screenshot%202015-07-24%2014.32.51.png?dl=0

and here's the stack:
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64206, result=0, data=Intent { (has extras) }} to activity {org.teleport.teleportmobile/org.teleport.teleportmobile.MainActivity}: java.lang.NullPointerException: println needs a message
at android.app.ActivityThread.deliverResults(ActivityThread.java:3659)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3702)
at android.app.ActivityThread.access$1300(ActivityThread.java:155)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5343)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Caused by: java.lang.NullPointerException: println needs a message
at android.util.Log.println_native_inner(Native Method)
at android.util.Log.println_native(Log.java:290)
at android.util.Log.e(Log.java:416)
at org.apache.cordova.facebook.ConnectPlugin.handleError(ConnectPlugin.java:647)
at org.apache.cordova.facebook.ConnectPlugin.access$300(ConnectPlugin.java:50)
at org.apache.cordova.facebook.ConnectPlugin$2.onCancel(ConnectPlugin.java:120)
at com.facebook.login.LoginManager.finishLogin(LoginManager.java:509)
at com.facebook.login.LoginManager.onActivityResult(LoginManager.java:191)
at com.facebook.login.LoginManager$1.onActivityResult(LoginManager.java:139)
at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:82)
at org.apache.cordova.facebook.ConnectPlugin.onActivityResult(ConnectPlugin.java:225)
at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)
at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:320)
at android.app.Activity.dispatchActivityResult(Activity.java:6218)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3655)
... 10 more
```

**Comment by Shinzah** [comment]
Hi, same issue here, when a dialog is cancelled !

**Comment by jeduan** [comment]
Yep, I can confirm this issue, a fix is in the works.

**Comment by motusingh** [comment]
After receiving call in onActivity result in case of user cancel dialouge you can call 
 if (mGoogleApiClient != null) {
            mGoogleApiClient.stopAutoManage((FragmentActivity)googleLoginActivity);
        }

its work for me.
