### ISSUE TITLE
Not understandable issue: Black screen on device.

### ISSUE THREAD

**Issue by clemdesign** [jeduan/cordova-plugin-facebook4#701]
**Bug or feature request**

[ X] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

Seen yesterday, when I build and run my App on device, this one fails with a black screen.

After many tests, it seems that this plugin impact the operation of App. But I don't know how and why.

If can I have help to understand this behavior please?

I have extracted the stack of main thread with the version where the App works and the Apps fails.

## App Works

> main thread is Runnable.

```
  at android.os.MessageQueue.nativePollOnce(Native Method)	
  at android.os.MessageQueue.next(MessageQueue.java:325)	
  at android.os.Looper.loop(Looper.java:142)	
  at android.app.ActivityThread.main(ActivityThread.java:6944)	
  at java.lang.reflect.Method.invoke(Native Method)	
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)	
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)	
```

## App fails

> main thread is Wait.

```
  at java.lang.Object.wait(Native Method)	
  at java.lang.Thread.parkFor$(Thread.java:2135)	
  at sun.misc.Unsafe.park(Unsafe.java:358)	
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)	
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)	
  at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)	
  at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)	
  at com.facebook.internal.AttributionIdentifiers$GoogleAdServiceConnection.getBinder(AttributionIdentifiers.java:283)	
  at com.facebook.internal.AttributionIdentifiers.getAndroidIdViaService(AttributionIdentifiers.java:150)	
  at com.facebook.internal.AttributionIdentifiers.getAndroidId(AttributionIdentifiers.java:77)	
  at com.facebook.internal.AttributionIdentifiers.getAttributionIdentifiers(AttributionIdentifiers.java:178)	
  at com.facebook.marketing.internal.RemoteConfigManager.loadRemoteConfig(RemoteConfigManager.java:54)	
  at com.facebook.marketing.internal.MarketingInitProvider.setupCodeless(MarketingInitProvider.java:65)	
  at com.facebook.marketing.internal.MarketingInitProvider.onCreate(MarketingInitProvider.java:49)	
  at android.content.ContentProvider.attachInfo(ContentProvider.java:1925)	
  at android.content.ContentProvider.attachInfo(ContentProvider.java:1900)	
  at android.app.ActivityThread.installProvider(ActivityThread.java:6578)	
  at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133)	
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043)	
  at android.app.ActivityThread.-wrap1(Unknown Source)	
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)	
  at android.os.Handler.dispatchMessage(Handler.java:105)	
  at android.os.Looper.loop(Looper.java:164)	
  at android.app.ActivityThread.main(ActivityThread.java:6944)	
  at java.lang.reflect.Method.invoke(Native Method)	
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)	
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by peterpeterparker** [comment]
You are looking for support, plz other channels to do so, like the Ionic forum or Stackoverflow

Except that, unfortunately I don't remember exactly how anymore, but I was facing that kind of problem recently too when I was playing with my Android platform. I think I finally overcome the problem by removing some plugins (like push notification and facebook4), removing my platform, adding it again and then adding one by one the removed plugin and paying attention to the dependencies, I think the root was some incompatibility (as often). You could check your `project.properties` in your android platform to have a look, maybe you will some incompatibility directly

I hope this helps a bit at least

Good luck
