### ISSUE TITLE
The plugin not work for framework7,

### ISSUE THREAD

**Issue by cyrusonline** [jeduan/cordova-plugin-facebook4#719]
the plugin not work for framework7, When add in framework7 cordova vue,
it will prompt the following error Are there any example code to deal with this problem? 

Thanks

BUILD FAILED in 14s
at ChildProcess.whenDone (E:\f7project\fblogin\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:925:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:33516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch()

**Comment by peterpeterparker** [comment]
Nothing we could do here, the plugin has nothing to do with any Frameworks except Cordova

According your stacktrace I would say you have a local problem in your project, for support request plz use other channels like Stackoverflow, thx in advance
