### ISSUE TITLE
AppName with special character like &

### ISSUE THREAD

**Issue by maiido** [jeduan/cordova-plugin-facebook4#766]
**Bug or feature request**

I'm reporting a reproducible issue with the code

**Describe the Bug of feature request**

If the appname contains '&', the install failed
**Expected Behavior**

should work with special characters

**Additional Context**

Installing "cordova-plugin-facebook4" for android
Android Studio project detected
config file res/values/facebookconnect.xml requested for changes not found at /Users/test/cordovaApp/platforms/android/res/values/facebookconnect.xml, ignoring
config file res/values/facebookconnect.xml requested for changes not found at /Users/test/cordovaApp/platforms/android/res/values/facebookconnect.xml, ignoring
config file res/values/facebookconnect.xml requested for changes not found at /Users/test/cordovaApp/platforms/android/res/values/facebookconnect.xml, ignoring
Failed to install 'cordova-plugin-facebook4': TypeError: Cannot read property 'trim' of null
   at Object.equalNodes (/Users/test/cordovaApp/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:40:29)
   at uniqueChild (/Users/test/cordovaApp/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:234:32)
   at /Users/test/cordovaApp/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:76:17
   at Array.forEach (<anonymous>)
   at Object.graftXML (/Users/test/cordovaApp/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:74:15)
   at ConfigFile_graft_child [as graft_child] (/Users/test/cordovaApp/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js:119:42)
   at PlatformMunger_apply_file_munge [as apply_file_munge] (/Users/test/cordovaApp/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:81:34)
   at munge_helper (/Users/test/cordovaApp/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:238:14)
   at PlatformMunger.add_plugin_changes (/Users/test/cordovaApp/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:159:12)
   at /Users/test/cordovaApp/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:123:29
Cannot read property 'trim' of null

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out https://www.npmjs.com/package/cordova-plugin-facebook-connect for the fork that is actively maintained. The README of that plugin has been updated to note that you must escape special characters like ampersands, as the APP_NAME is used in XML.
