### ISSUE TITLE
Build fails on iOS with error code 65

### ISSUE THREAD

**Issue by Hissvard** [jeduan/cordova-plugin-facebook4#830]
**Bug or feature request**

[x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

`phonegap build ios` fails with the following error message:
```
The following build commands failed:
	CompileC /Users/user/Library/Developer/Xcode/DerivedData/MyApp-dtsdztgswtsnnubosnumqjssdpaj/Build/Intermediates.noindex/MyApp\ App.build/Debug-iphonesimulator/MyApp\ App.build/Objects-normal/x86_64/FacebookConnectPlugin.o /Applications/MAMP/htdocs/MyApp/platforms/ios/MyApp\ App/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Command finished with error code 65: xcodebuild -workspace,MyApp.xcworkspace,-scheme,MyApp,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 11 Pro Max,build,CONFIGURATION_BUILD_DIR=/Applications/MAMP/htdocs/MyApp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Applications/MAMP/htdocs/MyApp/platforms/ios/build/sharedpch


(node:3817) UnhandledPromiseRejectionWarning: Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Applications/MAMP/htdocs/MyApp/node_modules/cordova-common/src/superspawn.js:135:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

(node:3817) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3817) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Plugin version, OS, devices, etc**

phonegap cli: 8.0.0
cordova-ios: 5.0.1
phonegap-plugin-facebook4: 6.2.0

**Additional Context**

I managed to solve the issue by manually editing my Podfile and adding the following lines to it, then running `cd platforms/ios && pod install`:
```
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
```
After that, `phonegap build ios` completed succesfully.

Could it be that somehow native dependencies aren't being added?

**Comment by peterpeterparker** [comment]
Plz use other channels for support request.

Double check the iOS documentation and other Xcode POD closed issues which sometimes contains local resolutions https://github.com/jeduan/cordova-plugin-facebook4/issues?utf8=✓&q=FBSDKCoreKit.h
