### ISSUE TITLE
Issues with android Versioning

### ISSUE THREAD

**Issue by KeKs0r** [jeduan/cordova-plugin-facebook4#9]
Hi,

I am not sure why exactly but the plugin is complaining in Phonegap Build that the version is not supported:

```
Error - Plugin error (you probably need to remove plugin files from your app): 
npm http GET https://registry.npmjs.org/cordova-plugin-facebook4/1.0.1 
npm http 200 https://registry.npmjs.org/cordova-plugin-facebook4/1.0.1 
npm http GET https://registry.npmjs.org/cordova-plugin-facebook4/-/cordova-plugin-facebook4-1.0.1.tgz 
npm http 200 https://registry.npmjs.org/cordova-plugin-facebook4/-/cordova-plugin-facebook4-1.0.1.tgz 
Failed to install 'cordova-plugin-facebook4':CordovaError: 
Plugin doesn't support this project's cordova-android version. cordova-android: 3.6.3, failed version requirement: >=4.0.0-dev 
at checkEngines (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/install.js:116:29) 
at /home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/install.js:289:16 
at _fulfilled (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:787:54) 
at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:816:30) 
at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:749:13) 
at /home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:557:44 
at flush (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:108:17) 
at process._tickCallback (node.js:442:13) 
Plugin doesn't support this project's cordova-android version. cordova-android: 3.6.3, failed version requirement: >=4.0.0-dev
```

Which confuses me since I am using 3.6.3 and this plugin requires > 4. Could you maybe change it from -dev to just > 4. Maybe that would help.

**Comment by jeduan** [comment]
Yep, I'm only supporting `cordova-android` v 4.0 or greater in this fork which was released back in April 2015.

**Comment by KeKs0r** [comment]
Does the plugin need a cradle build? 
Since I can't build even with an android version > 4.0

**Comment by jeduan** [comment]
Cradle build?

**Comment by KeKs0r** [comment]
Sorry Typo: Gradle, because PGB only supports ANT.

**Comment by jeduan** [comment]
Oh yeah it's using gradle to install the Facebook SDK and its dependencies. I guess there could be a way to tackle that using ant/maven but that's not currently on my roadmap. If you do that please send a pull request.

**Comment by KeKs0r** [comment]
I unfortunately have no experience in any of those tools. I am a plain web / frontend developer. So thats unfortunately not in my skillset. I probably just try to find a solution and build myself to not face that issue.
